erDiagram
  BRANCH ||--o{ BRANCHPROGRAM : Branch
  BRANCH ||--o{ BRANCHPROGRAM : BranchPrograms
  BRANCH ||--o{ CLASS : Branch
  BRANCH ||--o{ CLASS : Classes
  BRANCH ||--o{ CLASSROOM : Branch
  BRANCH ||--o{ CLASSROOM : Classrooms
  BRANCH ||--o{ INVOICE : Branch
  BRANCH ||--o{ INVOICE : Invoices
  BRANCH ||--o{ LEAD : BranchPreferenceNavigation
  BRANCH ||--o{ LEAD : PreferredLeads
  BRANCH ||--o{ MEDIAASSET : Branch
  BRANCH ||--o{ MEDIAASSET : MediaAssets
  BRANCH ||--o{ REGISTRATION : Branch
  BRANCH ||--o{ SESSION : Branch
  BRANCH ||--o{ SESSION : Sessions
  BRANCH ||--o{ TICKET : Branch
  BRANCH ||--o{ TICKET : Tickets
  BRANCH ||--o{ USER : Branch
  BRANCH ||--o{ USER : Users
  CLASS ||--o{ BRANCHPROGRAM : DefaultMakeupClass
  CLASS ||--o{ CLASSENROLLMENT : Class
  CLASS ||--o{ CLASSENROLLMENT : ClassEnrollments
  CLASS ||--o{ INVOICE : Class
  CLASS ||--o{ INVOICE : Invoices
  CLASS ||--o{ MEDIAASSET : Class
  CLASS ||--o{ MEDIAASSET : MediaAssets
  CLASS ||--o{ PLACEMENTTEST : Class
  CLASS ||--o{ PLACEMENTTEST : PlacementTests
  CLASS ||--o{ SESSION : Class
  CLASS ||--o{ SESSION : Sessions
  CLASS ||--o{ TICKET : Class
  CLASS ||--o{ TICKET : Tickets
  CLASSROOM ||--o{ CLASS : Room
  CLASSROOM ||--o{ PLACEMENTTEST : PlacementRoom
  CLASSROOM ||--o{ SESSION : ActualRoom
  CLASSROOM ||--o{ SESSION : ActualRoomSessions
  CLASSROOM ||--o{ SESSION : PlannedRoom
  CLASSROOM ||--o{ SESSION : PlannedRoomSessions
  INVOICE ||--o{ PAYMENT : Invoice
  INVOICE ||--o{ PAYMENT : Payments
  LEAD ||--o{ PLACEMENTTEST : Lead
  LEAD ||--o{ PLACEMENTTEST : PlacementTests
  NOTIFICATIONTEMPLATE ||--o{ NOTIFICATION : NotificationTemplate
  PLACEMENTTEST ||--o{ PLACEMENTTEST : OriginalPlacementTest
  PROFILE ||--o{ ATTENDANCE : Attendances
  PROFILE ||--o{ ATTENDANCE : StudentProfile
  PROFILE ||--o{ CLASSENROLLMENT : ClassEnrollments
  PROFILE ||--o{ CLASSENROLLMENT : StudentProfile
  PROFILE ||--o{ INVOICE : Invoices
  PROFILE ||--o{ INVOICE : StudentProfile
  PROFILE ||--o{ MEDIAASSET : MediaAssets
  PROFILE ||--o{ MEDIAASSET : StudentProfile
  PROFILE ||--o{ NOTIFICATION : ReceivedNotifications
  PROFILE ||--o{ NOTIFICATION : RecipientProfile
  PROFILE ||--o{ PARENTSTUDENTLINK : ParentLinks
  PROFILE ||--o{ PARENTSTUDENTLINK : ParentProfile
  PROFILE ||--o{ PARENTSTUDENTLINK : StudentLinks
  PROFILE ||--o{ PARENTSTUDENTLINK : StudentProfile
  PROFILE ||--o{ PLACEMENTTEST : PlacementTests
  PROFILE ||--o{ PLACEMENTTEST : StudentProfile
  PROFILE ||--o{ REGISTRATION : StudentProfile
  PROFILE ||--o{ TICKET : OpenedByProfile
  PROFILE ||--o{ TICKET : OpenedTickets
  PROFILE ||--o{ TICKETCOMMENT : CommenterProfile
  PROFILE ||--o{ TICKETCOMMENT : TicketComments
  PROGRAM ||--o{ BRANCHPROGRAM : BranchPrograms
  PROGRAM ||--o{ BRANCHPROGRAM : Program
  PROGRAM ||--o{ CLASS : Classes
  PROGRAM ||--o{ CLASS : Program
  PROGRAM ||--o{ PLACEMENTTEST : PrimaryPlacementTestRecommendations
  PROGRAM ||--o{ PLACEMENTTEST : SecondaryPlacementTestRecommendations
  PROGRAM ||--o{ REGISTRATION : Program
  PROGRAM ||--o{ REGISTRATION : SecondaryProgram
  PROGRAM ||--o{ TUITIONPLAN : Program
  PROGRAM ||--o{ TUITIONPLAN : TuitionPlans
  REGISTRATION ||--o{ CLASSENROLLMENT : Registration
  REGISTRATION ||--o{ REGISTRATION : OriginalRegistration
  SESSION ||--o{ ATTENDANCE : Attendances
  SESSION ||--o{ ATTENDANCE : Session
  TICKET ||--o{ TICKETCOMMENT : Ticket
  TICKET ||--o{ TICKETCOMMENT : TicketComments
  TUITIONPLAN ||--o{ CLASSENROLLMENT : ClassEnrollments
  TUITIONPLAN ||--o{ CLASSENROLLMENT : TuitionPlan
  TUITIONPLAN ||--o{ REGISTRATION : TuitionPlan
  USER ||--o{ ATTENDANCE : MarkedAttendances
  USER ||--o{ ATTENDANCE : MarkedByUser
  USER ||--o{ BLOG : CreatedByUser
  USER ||--o{ CLASS : AssistantTeacher
  USER ||--o{ CLASS : AssistantTeacherClasses
  USER ||--o{ CLASS : MainTeacher
  USER ||--o{ CLASS : MainTeacherClasses
  USER ||--o{ INVOICE : IssuedByUser
  USER ||--o{ INVOICE : IssuedInvoices
  USER ||--o{ LEAD : OwnedLeads
  USER ||--o{ LEAD : OwnerStaffUser
  USER ||--o{ MEDIAASSET : ApprovedByUser
  USER ||--o{ MEDIAASSET : UploadedMediaAssets
  USER ||--o{ MEDIAASSET : UploaderUser
  USER ||--o{ NOTIFICATION : ReceivedNotifications
  USER ||--o{ NOTIFICATION : RecipientUser
  USER ||--o{ PAYMENT : ConfirmedByUser
  USER ||--o{ PAYMENT : ConfirmedPayments
  USER ||--o{ PLACEMENTTEST : InvigilatedPlacementTests
  USER ||--o{ PLACEMENTTEST : InvigilatorUser
  USER ||--o{ PROFILE : Profiles
  USER ||--o{ PROFILE : User
  USER ||--o{ SESSION : ActualAssistant
  USER ||--o{ SESSION : ActualAssistantSessions
  USER ||--o{ SESSION : ActualTeacher
  USER ||--o{ SESSION : ActualTeacherSessions
  USER ||--o{ SESSION : PlannedAssistant
  USER ||--o{ SESSION : PlannedAssistantSessions
  USER ||--o{ SESSION : PlannedTeacher
  USER ||--o{ SESSION : PlannedTeacherSessions
  USER ||--o{ TICKET : AssignedTickets
  USER ||--o{ TICKET : AssignedToUser
  USER ||--o{ TICKET : OpenedByUser
  USER ||--o{ TICKET : OpenedTickets
  USER ||--o{ TICKETCOMMENT : CommenterUser
  USER ||--o{ TICKETCOMMENT : TicketComments
